name: "Pysplashsurf Tests"
on: 
- workflow_dispatch

jobs:
  test:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: pysplashsurf/python_environment.yaml
        init-shell: >-
          bash
    - run: |
        conda info
        conda list
    - name: Build wheels
      uses: PyO3/maturin-action@v1
      with:
        target: x86_64
        args: --release --out dist -m pysplashsurf/Cargo.toml
        manylinux: auto
    - name: Get wheel name
      id: get_filename
      run: |
        FILE_NAME=$(ls dist)
        echo "Found file: $FILE_NAME"
        echo "file_name=$FILE_NAME" >> $GITHUB_OUTPUT
    - run: pip install dist/${{ steps.get_filename.outputs.file_name }}
    - name: Install splashsurf CLI
      run: cargo install splashsurf
    - name: Run pytest
      uses: pavelzw/pytest-action@v2
      with:
        verbose: true
        emoji: false
        job-summary: true
        click-to-expand: true
        report-title: 'Pytest Report'